// Time
export const PASS_MINUTES = 'PASS_MINUTES';

// Live Stats
export const UPDATE_HEALTH = 'UPDATE_HEALTH';
export const UPDATE_SLEEP = 'UPDATE_SLEEP';
export const UPDATE_HUNGER = 'UPDATE_HUNGER';
export const UPDATE_MOOD = 'UPDATE_MOOD';
export const UPDATE_CLEANLINESS = 'UPDATE_CLEANLINESS';
export const UPDATE_AROUSAL = 'UPDATE_AROUSAL';

// Location
export const UPDATE_CURRENT_DESCRIPTION = 'UPDATE_CURRENT_DESCRIPTION';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const UPDATE_VISIBLE_LOCATIONS = 'UPDATE_VISIBLE_LOCATIONS';
export const UPDATE_INSIDE_LOCATION = 'UPDATE_INSIDE_LOCATION';

// Current Media Displayed
export const UPDATE_CURRENT_MEDIA = 'UPDATE_CURRENT_MEDIA';
