// Time
export const PASS_TIME = 'PASS_TIME';

// Live Stats
export const UPDATE_SLEEP = 'UPDATE_SLEEP';
export const UPDATE_HUNGER = 'UPDATE_HUNGER';

// Location
export const UPDATE_CURRENT_IMAGE = 'UPDATE_CURRENT_IMAGE';
export const UPDATE_CURRENT_DESCRIPTION = 'UPDATE_CURRENT_DESCRIPTION';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const UPDATE_VISIBLE_LOCATIONS = 'UPDATE_VISIBLE_LOCATIONS';
